.TH "ActiveObject" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActiveObject \- \fBActiveObject\fP - Set of \fBDynamicObject\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <object\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "\fBDynamicObject\fP * \fBparts\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBActiveObject\fP - Set of \fBDynamicObject\fP\&. 

Used in animated objects\&. 
.PP
\fBFile format:\fP
.RS 4
aobj 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBActiveObjectInstance\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
