.TH "ActiveObjectInstance" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActiveObjectInstance \- Instance of a \fBActiveObject\fP logically\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <object\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBactivePart\fP"
.br
.ti -1c
.RI "GLfloat \fBposition\fP [3]"
.br
.ti -1c
.RI "GLfloat \fBrotation\fP [3]"
.br
.ti -1c
.RI "GLfloat \fBscale\fP [3]"
.br
.ti -1c
.RI "GLboolean \fBvisible\fP"
.br
.ti -1c
.RI "\fBActiveObject\fP * \fBobject\fP"
.br
.ti -1c
.RI "GLfloat \fBmoveMat\fP [16]"
.br
.ti -1c
.RI "\fBReferencePoint\fP * \fBreference\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Instance of a \fBActiveObject\fP logically\&. 


.PP
\fBSee also:\fP
.RS 4
\fBActiveObject\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
