.TH "Action" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Action \- \fBAction\fP instance\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <map\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GLint \fBid\fP"
.br
.RI "It not required to be unique\&. "
.ti -1c
.RI "\fBActionType\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBGenericType\fP * \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAction\fP instance\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
