.TH "CameraInfo" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CameraInfo \- Game camera info storage\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <game\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GLfloat \fBrotation\fP [3]"
.br
.ti -1c
.RI "GLfloat \fBposition\fP [3]"
.br
.ti -1c
.RI "GLfloat \fBprojMat\fP [16]"
.br
.ti -1c
.RI "GLfloat \fBviewMat\fP [16]"
.br
.ti -1c
.RI "GLfloat \fBdestinationRotation\fP [3]"
.br
.ti -1c
.RI "GLfloat \fBdestinationPosition\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Game camera info storage\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
