.TH "Char" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Char \- Character object (used in \fBFont\fP families)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <font\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBcode\fP"
.br
.ti -1c
.RI "char \fBname\fP [32]"
.br
.ti -1c
.RI "GLuint \fBwidth\fP"
.br
.ti -1c
.RI "GLint \fBy\fP"
.br
.ti -1c
.RI "\fBLinkedList\fP * \fBparts\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Character object (used in \fBFont\fP families) 


.PP
\fBSee also:\fP
.RS 4
\fBFont\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
