.TH "CharPart" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CharPart \- Cube structure for character\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <font\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcolorId\fP"
.br
.RI "Index of the cube color\&. "
.ti -1c
.RI "\fBPartType\fP \fBtype\fP"
.br
.RI "Type of cube\&. "
.ti -1c
.RI "GLfloat \fBposition\fP [3]"
.br
.RI "\fBPosition\fP of the cube in the character\&. "
.in -1c
.SH "Detailed Description"
.PP 
Cube structure for character\&. 
.SH "Member Data Documentation"
.PP 
.SS "int CharPart::colorId"

.PP
Index of the cube color\&. Index 0 means dynamic\&. Dynamic color must be pass as an argument to the renderer function 

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
