.TH "Color" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Color \- RGBA color type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stdgame\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GLfloat \fBrgba\fP [4]"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   GLfloat \fBr\fP"
.br
.ti -1c
.RI "   GLfloat \fBg\fP"
.br
.ti -1c
.RI "   GLfloat \fBb\fP"
.br
.ti -1c
.RI "   GLfloat \fBa\fP"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
RGBA color type\&. 

The \fCcolor\&.rgba\fP returns a 4-dimensional GLfloat array, the \fCcolor\&.r\fP returns the red, the \fCcolor\&.g\fP returns green, the \fCcolor\&.b\fP return the blue and the \fCcolor\&.a\fPreturns the alpha component of the RGBA color\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
