.TH "Cursor" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cursor \- \fBCursor\fP object and info storage\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <object\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBActiveObject\fP * \fBcursorObject\fP"
.br
.ti -1c
.RI "\fBActiveObjectInstance\fP * \fBpointer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCursor\fP object and info storage\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
