.TH "DynamicObject" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DynamicObject \- \fBDynamicObject\fP - Movable object\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <object\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "GLfloat \fBposition\fP [3]"
.br
.ti -1c
.RI "GLfloat \fBrotation\fP [3]"
.br
.ti -1c
.RI "GLfloat \fBscale\fP [3]"
.br
.ti -1c
.RI "GLfloat \fBmoveMat\fP [16]"
.br
.ti -1c
.RI "\fBLinkedList\fP * \fBparts\fP"
.br
.ti -1c
.RI "\fBLinkedList\fP * \fBcolors\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBDynamicObject\fP - Movable object\&. 


.PP
\fBFile format:\fP
.RS 4
dobj 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBDynamicObjectInstance\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
