.TH "Entity" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Entity \- Mobs, monsters\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <map\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GLint \fBid\fP"
.br
.ti -1c
.RI "\fBActiveObjectInstance\fP * \fBobj\fP"
.br
.ti -1c
.RI "GLint \fBlightId\fP"
.br
.ti -1c
.RI "GLfloat \fBspellSpeed\fP"
.br
.ti -1c
.RI "GLfloat \fBdamage\fP"
.br
.ti -1c
.RI "GLfloat \fBhp\fP"
.br
.ti -1c
.RI "GLint \fBscore\fP"
.br
.ti -1c
.RI "GLfloat \fBfi0\fP"
.br
.ti -1c
.RI "GLfloat \fBradius\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Mobs, monsters\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
