.TH "EventRegion" 3 "Sat Dec 2 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EventRegion
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GLfloat \fBx1\fP"
.br
.ti -1c
.RI "GLfloat \fBy1\fP"
.br
.ti -1c
.RI "GLfloat \fBx2\fP"
.br
.ti -1c
.RI "GLfloat \fBy2\fP"
.br
.ti -1c
.RI "GLint \fBactionId\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
