.TH "Font" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Font \- \fBFont\fP family\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <font\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLinkedList\fP * \fBchars\fP"
.br
.ti -1c
.RI "\fBChar\fP * \fBunknown\fP"
.br
.ti -1c
.RI "GLfloat * \fBcolors\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBFont\fP family\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
