.TH "GameInstance" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameInstance \- It contains all the data that the game requires\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <game\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBShaderInfo\fP * \fBshader\fP"
.br
.ti -1c
.RI "\fBCameraInfo\fP * \fBcamera\fP"
.br
.ti -1c
.RI "\fBMap\fP * \fBmap\fP"
.br
.ti -1c
.RI "\fBLigingInfo\fP * \fBlighting\fP"
.br
.ti -1c
.RI "\fBPlayer\fP * \fBplayer\fP"
.br
.ti -1c
.RI "\fBFont\fP * \fBfont\fP"
.br
.ti -1c
.RI "\fBOptions\fP * \fBoptions\fP"
.br
.ti -1c
.RI "\fBCursor\fP * \fBcursor\fP"
.br
.ti -1c
.RI "GLuint \fBtileVAO\fP"
.br
.ti -1c
.RI "GLuint \fBblankTextureId\fP"
.br
.ti -1c
.RI "GLFWwindow * \fBwindow\fP"
.br
.ti -1c
.RI "\fBGameState\fP \fBstate\fP"
.br
.ti -1c
.RI "\fBLinkedList\fP * \fBreferencePoints\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
It contains all the data that the game requires\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
