.TH "GenericType" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericType \- Generic type variable\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <components\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBvalue\fP"
.br
.ti -1c
.RI "size_t \fBvalueLength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Generic type variable\&. 


.PP
\fBSee also:\fP
.RS 4
\fBnewGenericValue()\fP 
.PP
\fBnewGenericIntValue()\fP 
.PP
\fBnewGenericFloatValue()\fP 
.PP
\fBsetGenericValue()\fP 
.PP
\fBsetGenericIntValue()\fP 
.PP
\fBsetGenericFloatValue()\fP 
.PP
\fBgetGenericIntValue()\fP 
.PP
\fBgetGenericFloatValue()\fP 
.PP
\fBfreeGenericValue()\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
