.TH "HighScoreValue" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HighScoreValue \- Record file line\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <map\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBname\fP [255]"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "int \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Record file line\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
