.TH "ImageComponent" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImageComponent \- Image type component specific values\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <components\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GLuint \fBtextureId\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Image type component specific values\&. 


.PP
\fBTodo\fP
.RS 4
Unimplemented: \fBImageComponent\fP 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBComponent\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
