.TH "InputActionWrapper" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InputActionWrapper \- Input action key and mouse wrapper\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <game\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GLint \fBid\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Input action key and mouse wrapper\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
