.TH "Light" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Light \- Point light object\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <map\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GLint \fBid\fP"
.br
.ti -1c
.RI "GLfloat \fBposition\fP [3]"
.br
.ti -1c
.RI "GLfloat \fBstrength\fP"
.br
.ti -1c
.RI "GLfloat \fBcolor\fP [3]"
.br
.ti -1c
.RI "GLfloat \fBspecular\fP"
.br
.ti -1c
.RI "GLfloat \fBintensity\fP"
.br
.ti -1c
.RI "\fBReferencePoint\fP * \fBreference\fP"
.br
.ti -1c
.RI "GLboolean \fBvisible\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Point light object\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
