.TH "LigingInfo" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LigingInfo \- Finalized light info\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <game\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnumLights\fP"
.br
.ti -1c
.RI "GLfloat \fBlightPosition\fP [\fBMAX_NUM_LIGHTS\fP *3]"
.br
.ti -1c
.RI "GLfloat \fBlightColor\fP [\fBMAX_NUM_LIGHTS\fP *3]"
.br
.ti -1c
.RI "GLfloat \fBlightInfo\fP [\fBMAX_NUM_LIGHTS\fP *3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Finalized light info\&. 

These values will be sent to the GPU 

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
