.TH "LinkedList" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LinkedList \- Linked list header\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <linkedlist\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBdataSize\fP"
.br
.ti -1c
.RI "\fBListItem\fP * \fBfirst\fP"
.br
.ti -1c
.RI "\fBListItem\fP * \fBlast\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Linked list header\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
