.TH "ListItem" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ListItem \- List item\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <linkedlist\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "struct \fBListItem\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
List item\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
