.TH "md_docs_usermanual" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_docs_usermanual \- User manual 

.SS "\fBMenu\fP"
.PP
.IP "\(bu" 2
Start Game
.IP "  \(bu" 4
Select map: \fBMap\fP list
.IP "    \(bu" 6
Ingame
.PP

.PP

.IP "\(bu" 2
\fBOptions\fP
.IP "  \(bu" 4
Graphics: Graphical settings (MSAA, FullScreen, Camera movement, etc)
.IP "  \(bu" 4
Controls: Movement, spells, attack
.PP

.IP "\(bu" 2
Credits: Credits and license info
.IP "\(bu" 2
Exit: Quit game
.PP
.PP
.SS "Movement (with default settings)"
.PP
.IP "\(bu" 2
Go forward: \fCD\fP or \fCRight arrow\fP key
.IP "\(bu" 2
Go backward: \fCA\fP or \fCLeft arrow\fP key
.IP "\(bu" 2
Jump: \fCSpace\fP or \fCUp arrow\fP key
.IP "\(bu" 2
Sneek: \fCS\fP, \fCShift\fP or \fCDown arrow\fP key
.IP "\(bu" 2
Attack: \fCLeft mouse button, or any control\fP
.IP "\(bu" 2
\fBMenu\fP: \fCEsc\fP or \fCPause\fP
.IP "\(bu" 2
Spell1: \fCF1\fP or \fC1\fP
.IP "\(bu" 2
Spell2: \fCF2\fP or \fC2\fP
.IP "\(bu" 2
Spell3: \fCF3\fP or \fC3\fP
.PP
.PP
.SS "Fun facts:"
.PP
.RS 4
If you sneek you will be slower\&. 
.br
 You can do double jump by pressing the jump key in the air\&. 
.br
 Your feet doesn't need to be on the ground to jump\&. 
.RE
.PP
.PP
.SS "Items"
.PP
.IP "\(bu" 2
Key: You can grab the key and use it to open door
.IP "\(bu" 2
Coin: More coin equals more score
.PP
.PP
.SS "Traps"
.PP
.IP "\(bu" 2
Bottom spikes: If you fall into them, you will die\&.
.IP "\(bu" 2
Lava: You can't swim lava, I believe\&.
.IP "\(bu" 2
Top spikes: You must sneek to avoid death\&.
.PP
.PP
.SS "Mobs"
.PP
.IP "\(bu" 2
Ghost from pacman
.IP "\(bu" 2
Space invaders mob
.PP
.PP
.SS "Maps"
.PP
.IP "\(bu" 2
Tutorial
.IP "\(bu" 2
Pyramid (not included) 
.PP

