.TH "md_docs_howtoplay" 3 "Sun Nov 19 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_docs_howtoplay \- Game Instructions 

.SS "\fBMenu\fP"
.PP
.IP "\(bu" 2
Start Game
.IP "  \(bu" 4
Select map: \fBMap\fP list
.IP "    \(bu" 6
Ingame
.PP

.PP

.IP "\(bu" 2
\fBOptions\fP
.IP "  \(bu" 4
Graphics: Graphical settings (MSAA, FullScreen, Shadow, etc)
.IP "  \(bu" 4
Controls: Movement, spells,
.PP

.IP "\(bu" 2
Credits: Prints credits
.IP "\(bu" 2
Exit: Quit game
.PP
.PP
.SS "Movement (with default settings)"
.PP
.IP "\(bu" 2
Go forward: \fCD\fP or \fCRight arrow\fP key
.IP "\(bu" 2
Go backward: \fCA\fP or \fCLeft arrow\fP key
.IP "\(bu" 2
Jump: \fCSpace\fP or \fCUp arrow\fP key
.IP "\(bu" 2
Sneek: \fCS\fP, \fCShift\fP or \fCDown arrow\fP key
.IP "\(bu" 2
Attack: \fCLeft mouse button\fP
.PP
.PP
.SS "Items"
.PP
.IP "\(bu" 2
Key
.IP "\(bu" 2
Coin
.PP
.PP
.SS "Traps"
.PP
.SS "Mobs"
.PP
.SS "Maps"

