.TH "Menu" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Menu \- \fBMenu\fP object\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <menu\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "\fBLinkedList\fP * \fBcomponents\fP"
.br
.ti -1c
.RI "GLboolean \fBuseCursor\fP"
.br
.ti -1c
.RI "GLfloat \fBscrollMin\fP"
.br
.ti -1c
.RI "GLfloat \fBscrollMax\fP"
.br
.ti -1c
.RI "GLfloat \fBscrollOffset\fP"
.br
.ti -1c
.RI "void(* \fBonClick\fP )(\fBGameInstance\fP *)"
.br
.ti -1c
.RI "void(* \fBonScroll\fP )(\fBGameInstance\fP *, GLfloat)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBMenu\fP object\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
