.TH "src/menu.c" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/menu.c \- \fBComponent\fP, click and scroll manager\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'stdgame\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBsetOptionsDefaults\fP (\fBGameInstance\fP *this)"
.br
.RI "Initialize the options storage with the default values\&. "
.ti -1c
.RI "void \fBonClickMenu\fP (\fBGameInstance\fP *this)"
.br
.RI "onClick() - \fBMenu\fP click method "
.ti -1c
.RI "void \fBonScrollMenu\fP (\fBGameInstance\fP *this, GLfloat offset)"
.br
.RI "onScroll() - Scroll menu method "
.ti -1c
.RI "void \fBloadDefaultOptions\fP (\fBGameInstance\fP *this)"
.br
.RI "Creates the options file if not exists and loads the default options\&. "
.ti -1c
.RI "void \fBloadOptions\fP (\fBGameInstance\fP *this)"
.br
.RI "Load options from the options file is possible\&. "
.ti -1c
.RI "void \fBsaveOptions\fP (\fBGameInstance\fP *this)"
.br
.RI "Save modified options\&. "
.ti -1c
.RI "void \fBupdateControlsKey\fP (\fBGameInstance\fP *this, unsigned int key)"
.br
.RI "Controls key button processor\&. "
.ti -1c
.RI "void \fBupdateControlsMods\fP (\fBGameInstance\fP *this, int mods, int key)"
.br
.RI "Controls key modifier button processor\&. "
.ti -1c
.RI "GLboolean \fBupdateControllsMouse\fP (\fBGameInstance\fP *this, int button)"
.br
.RI "Controls mouse button processor\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBComponent\fP, click and scroll manager\&. 


.PP
\fBAuthor:\fP
.RS 4
Gerviba (Szabo Gergely) 
.RE
.PP
\fBHeader:\fP
.RS 4
\fBmenu\&.h\fP 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void loadDefaultOptions (\fBGameInstance\fP * this)"

.PP
Creates the options file if not exists and loads the default options\&. 
.PP
\fBParameters:\fP
.RS 4
\fIthis\fP Actual \fBGameInstance\fP instance 
.RE
.PP

.SS "void loadOptions (\fBGameInstance\fP * this)"

.PP
Load options from the options file is possible\&. 
.PP
\fBParameters:\fP
.RS 4
\fIthis\fP Actual \fBGameInstance\fP instance 
.RE
.PP

.SS "void onClickMenu (\fBGameInstance\fP * this)"

.PP
onClick() - \fBMenu\fP click method 
.PP
\fBParameters:\fP
.RS 4
\fIthis\fP Actual \fBGameInstance\fP instance 
.RE
.PP

.SS "void onScrollMenu (\fBGameInstance\fP * this, GLfloat offset)"

.PP
onScroll() - Scroll menu method 
.PP
\fBParameters:\fP
.RS 4
\fIthis\fP Actual \fBGameInstance\fP instance 
.br
\fIoffset\fP The Y-dim offset 
.RE
.PP

.SS "void saveOptions (\fBGameInstance\fP * this)"

.PP
Save modified options\&. 
.PP
\fBParameters:\fP
.RS 4
\fIthis\fP Actual \fBGameInstance\fP instance 
.RE
.PP

.SS "static void setOptionsDefaults (\fBGameInstance\fP * this)\fC [static]\fP"

.PP
Initialize the options storage with the default values\&. 
.PP
\fBParameters:\fP
.RS 4
\fIthis\fP Actual \fBGameInstance\fP instance 
.RE
.PP

.SS "GLboolean updateControllsMouse (\fBGameInstance\fP * this, int button)"

.PP
Controls mouse button processor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIthis\fP Actual \fBGameInstance\fP instance 
.br
\fIbutton\fP Mouse button id 
.RE
.PP

.SS "void updateControlsKey (\fBGameInstance\fP * this, unsigned int key)"

.PP
Controls key button processor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIthis\fP Actual \fBGameInstance\fP instance 
.br
\fIkey\fP Key code 
.RE
.PP

.SS "void updateControlsMods (\fBGameInstance\fP * this, int mods, int key)"

.PP
Controls key modifier button processor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIthis\fP Actual \fBGameInstance\fP instance 
.br
\fImods\fP Modifiers 
.br
\fIkey\fP Key code 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
