.TH "Message" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Message \- Text message (rendered as 3D object)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <map\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPosition\fP \fBposition\fP"
.br
.ti -1c
.RI "\fBColor\fP \fBcolor\fP"
.br
.ti -1c
.RI "\fBFontSize\fP \fBsize\fP"
.br
.ti -1c
.RI "char \fBmessage\fP [100]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Text message (rendered as 3D object) 

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
