.TH "MessageRegion" 3 "Sun Dec 3 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MessageRegion
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPosition\fP \fBposition\fP"
.br
.ti -1c
.RI "char \fBmessage1\fP [100]"
.br
.ti -1c
.RI "char \fBmessage2\fP [100]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
