.TH "ObjectInfo" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectInfo \- Object storage\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <object\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLinkedList\fP * \fBstaticObjects\fP"
.br
.ti -1c
.RI "\fBLinkedList\fP * \fBstaticInstances\fP"
.br
.ti -1c
.RI "\fBLinkedList\fP * \fBdynamicObjects\fP"
.br
.ti -1c
.RI "\fBLinkedList\fP * \fBdynamicInstances\fP"
.br
.ti -1c
.RI "\fBLinkedList\fP * \fBactiveObjects\fP"
.br
.ti -1c
.RI "\fBLinkedList\fP * \fBactiveInstances\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Object storage\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
