.TH "ObjectComponent" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectComponent \- Object type component specific values\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <components\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBActiveObjectInstance\fP * \fBobject\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Object type component specific values\&. 

Active object as a component
.PP
\fBSee also:\fP
.RS 4
\fBActiveObjectInstance\fP 
.PP
\fBComponent\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
