.TH "src/object.c" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/object.c \- Static, dynamic and active object loader and renderer\&. \fBReferencePoint\fP manager\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'stdgame\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBStaticObject\fP * \fBloadStaticObject\fP (char path[])"
.br
.RI "Load static object\&. "
.ti -1c
.RI "\fBDynamicObject\fP * \fBloadDynamicObject\fP (char path[])"
.br
.RI "Load dynamic object\&. "
.ti -1c
.RI "\fBActiveObject\fP * \fBloadActiveObject\fP (char path[])"
.br
.RI "Load active object\&. "
.ti -1c
.RI "void \fBrenderStaticObject\fP (\fBGameInstance\fP *this, \fBStaticObjectInstance\fP *instance)"
.br
.RI "Render static object\&. "
.ti -1c
.RI "void \fBrenderDynamicObject\fP (\fBGameInstance\fP *this, \fBDynamicObjectInstance\fP *instance)"
.br
.RI "Render dynamic object\&. "
.ti -1c
.RI "void \fBrenderActiveObject\fP (\fBGameInstance\fP *this, \fBActiveObjectInstance\fP *instance)"
.br
.RI "Render active object\&. "
.ti -1c
.RI "void \fBrenderTile\fP (\fBGameInstance\fP *this, \fBTile\fP *tile)"
.br
.RI "Render map tile\&. "
.ti -1c
.RI "void \fBinitStraticInstance\fP (\fBStaticObjectInstance\fP *instance)"
.br
.RI "Calculate the move matrix of the static object instance\&. "
.ti -1c
.RI "void \fBinitReferencePoints\fP (\fBGameInstance\fP *this)"
.br
.RI "Initialize reference points\&. "
.ti -1c
.RI "void \fBupdateReferencePoint\fP (\fBGameInstance\fP *this, GLfloat delta)"
.br
.RI "Update reference points\&. "
.in -1c
.SH "Detailed Description"
.PP 
Static, dynamic and active object loader and renderer\&. \fBReferencePoint\fP manager\&. 


.PP
\fBAuthor:\fP
.RS 4
Gerviba (Szabo Gergely) 
.RE
.PP
\fBHeader:\fP
.RS 4
\fBobject\&.h\fP 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void initReferencePoints (\fBGameInstance\fP * this)"

.PP
Initialize reference points\&. 
.PP
\fBParameters:\fP
.RS 4
\fIthis\fP Actual \fBGameInstance\fP instance 
.RE
.PP

.SS "void initStraticInstance (\fBStaticObjectInstance\fP * instance)"

.PP
Calculate the move matrix of the static object instance\&. 
.PP
\fBParameters:\fP
.RS 4
\fIinstance\fP Object instance to init 
.RE
.PP

.SS "\fBActiveObject\fP* loadActiveObject (char path[])"

.PP
Load active object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The path of the file 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBActiveObject\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
Loaded \fBActiveObject\fP 
.RE
.PP

.SS "\fBDynamicObject\fP* loadDynamicObject (char path[])"

.PP
Load dynamic object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The path of the file 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBDynamicObject\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
Loaded \fBDynamicObject\fP 
.RE
.PP

.SS "\fBStaticObject\fP* loadStaticObject (char path[])"

.PP
Load static object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP The path of the file 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBStaticObject\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
Loaded \fBStaticObject\fP 
.RE
.PP

.SS "void renderActiveObject (\fBGameInstance\fP * this, \fBActiveObjectInstance\fP * instance)"

.PP
Render active object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIthis\fP Actual \fBGameInstance\fP instance 
.br
\fIinstance\fP Object instance to render 
.RE
.PP

.SS "void renderDynamicObject (\fBGameInstance\fP * this, \fBDynamicObjectInstance\fP * instance)"

.PP
Render dynamic object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIthis\fP Actual \fBGameInstance\fP instance 
.br
\fIinstance\fP Object instance to render 
.RE
.PP

.SS "void renderStaticObject (\fBGameInstance\fP * this, \fBStaticObjectInstance\fP * instance)"

.PP
Render static object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIthis\fP Actual \fBGameInstance\fP instance 
.br
\fIinstance\fP Object instance to render 
.RE
.PP

.SS "void renderTile (\fBGameInstance\fP * this, \fBTile\fP * tile)"

.PP
Render map tile\&. 
.PP
\fBParameters:\fP
.RS 4
\fIthis\fP Actual \fBGameInstance\fP instance 
.br
\fItile\fP \fBTile\fP to render 
.RE
.PP

.SS "void updateReferencePoint (\fBGameInstance\fP * this, GLfloat delta)"

.PP
Update reference points\&. 
.PP
\fBParameters:\fP
.RS 4
\fIthis\fP Actual \fBGameInstance\fP instance 
.br
\fIdelta\fP Ellapsed time 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
