.TH "Options" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Options \- \fBOptions\fP storage\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <game\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GLint \fBmsaa\fP"
.br
.ti -1c
.RI "GLboolean \fBfullscreen\fP"
.br
.ti -1c
.RI "GLint \fBheight\fP"
.br
.ti -1c
.RI "GLint \fBwidth\fP"
.br
.ti -1c
.RI "GLint \fBwindowedHeight\fP"
.br
.ti -1c
.RI "GLint \fBwindowedWidth\fP"
.br
.ti -1c
.RI "GLboolean \fBshadow\fP"
.br
.ti -1c
.RI "GLboolean \fBcameraMovement\fP"
.br
.ti -1c
.RI "GLfloat \fBtanFov\fP"
.br
.ti -1c
.RI "GLfloat \fBaspectRatio\fP"
.br
.ti -1c
.RI "\fBInputActionWrapper\fP \fBmoveLeft\fP"
.br
.ti -1c
.RI "\fBInputActionWrapper\fP \fBmoveRight\fP"
.br
.ti -1c
.RI "\fBInputActionWrapper\fP \fBjump\fP"
.br
.ti -1c
.RI "\fBInputActionWrapper\fP \fBsneek\fP"
.br
.ti -1c
.RI "\fBInputActionWrapper\fP \fBattack\fP"
.br
.ti -1c
.RI "\fBInputActionWrapper\fP \fBuse\fP"
.br
.ti -1c
.RI "\fBInputActionWrapper\fP \fBspell1\fP"
.br
.ti -1c
.RI "\fBInputActionWrapper\fP \fBspell2\fP"
.br
.ti -1c
.RI "\fBInputActionWrapper\fP \fBspell3\fP"
.br
.ti -1c
.RI "\fBInputActionWrapper\fP \fBmenu\fP"
.br
.ti -1c
.RI "\fBComponent\fP * \fBselectedToSet\fP"
.br
.ti -1c
.RI "GLboolean \fBreloadProgram\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBOptions\fP storage\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
