.TH "PartColor" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PartColor \- \fBColor\fP of a cube\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <object\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "GLfloat \fBcolor\fP [4]"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBColor\fP of a cube\&. 

Stored in color banks\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
