.TH "PhysicsArea" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PhysicsArea \- Physics area\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <map\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GLint \fBid\fP"
.br
.ti -1c
.RI "GLfloat \fBx\fP"
.br
.ti -1c
.RI "GLfloat \fBy\fP"
.br
.ti -1c
.RI "GLboolean \fBenabled\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Physics area\&. 

Players can't enter if it is enabled 

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
