.TH "Player" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player \- \fBPlayer\fP type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <player\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "GLfloat \fBposition\fP [3]"
.br
.ti -1c
.RI "GLfloat \fBvelocity\fP [3]"
.br
.ti -1c
.RI "GLfloat \fBheight\fP"
.br
.ti -1c
.RI "GLfloat \fBwidth\fP"
.br
.ti -1c
.RI "GLuint \fBjump\fP"
.br
.ti -1c
.RI "double \fBlastJump\fP"
.br
.ti -1c
.RI "\fBActiveObjectInstance\fP * \fBmodel\fP"
.br
.ti -1c
.RI "GLboolean \fBsneek\fP"
.br
.ti -1c
.RI "GLboolean \fBleftSide\fP"
.br
.ti -1c
.RI "GLint \fBitem\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBPlayer\fP type\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
