.TH "src/player.h" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/player.h \- \fBPlayer\fP specific types and functions (header)  

.SH SYNOPSIS
.br
.PP
\fC#include <time\&.h>\fP
.br
\fC#include 'stdgame\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBPlayer\fP"
.br
.RI "\fBPlayer\fP type\&. "
.ti -1c
.RI "struct \fBSpell\fP"
.br
.RI "\fBSpell\fP type\&. "
.ti -1c
.RI "struct \fBSpells\fP"
.br
.RI "\fBSpells\fP storage\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPLAYER_SPEED\fP   2\&.3"
.br
.ti -1c
.RI "#define \fBPLAYER_JUMP\fP   0\&.6"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitPlayer\fP (\fBGameInstance\fP *this)"
.br
.RI "Initialze player\&. "
.ti -1c
.RI "void \fBfreePlayer\fP (\fBGameInstance\fP *this)"
.br
.RI "Free player\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBPlayer\fP specific types and functions (header) 


.PP
\fBAuthor:\fP
.RS 4
Gerviba (Szabo Gergely) 
.RE
.PP
\fBDefinition:\fP
.RS 4
\fBplayer\&.c\fP 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void freePlayer (\fBGameInstance\fP * this)"

.PP
Free player\&. 
.PP
\fBParameters:\fP
.RS 4
\fIthis\fP Actual \fBGameInstance\fP instance 
.RE
.PP

.SS "void initPlayer (\fBGameInstance\fP * this)"

.PP
Initialze player\&. 
.PP
\fBParameters:\fP
.RS 4
\fIthis\fP Actual \fBGameInstance\fP instance 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
