.TH "Position" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Position \- 3D position type  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stdgame\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GLfloat \fBxyz\fP [3]"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   GLfloat \fBx\fP"
.br
.ti -1c
.RI "   GLfloat \fBy\fP"
.br
.ti -1c
.RI "   GLfloat \fBz\fP"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
3D position type 

The \fCposition\&.xyz\fP returns a 3-dimensional GLfloat array, and \fCposition\&.x\fP, \fCposition\&.y\fP and \fCposition\&.z\fP returns a component of the selected dimension\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
