.TH "ReferencePoint" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReferencePoint \- Dynamically changing reference points for animations\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <object\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GLint \fBid\fP"
.br
.ti -1c
.RI "GLfloat \fBposition\fP [3]"
.br
.ti -1c
.RI "GLfloat \fBrotation\fP [3]"
.br
.ti -1c
.RI "GLfloat \fBscale\fP [3]"
.br
.ti -1c
.RI "GLfloat \fBtiming\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Dynamically changing reference points for animations\&. 


.PP
\fBSee also:\fP
.RS 4
fileformats\&.md 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
