.TH "Region" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Region \- \fBAction\fP activator region\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <map\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GLfloat \fBxMin\fP"
.br
.ti -1c
.RI "GLfloat \fByMin\fP"
.br
.ti -1c
.RI "GLfloat \fBxMax\fP"
.br
.ti -1c
.RI "GLfloat \fByMax\fP"
.br
.ti -1c
.RI "GLint \fBactionId\fP"
.br
.ti -1c
.RI "GLint \fBmaxUse\fP"
.br
.ti -1c
.RI "GLint \fBitemReq\fP"
.br
.ti -1c
.RI "GLboolean \fBnotSneek\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAction\fP activator region\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
