.TH "ShaderInfo" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ShaderInfo \- Shader program uniform ids\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <game\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GLuint \fBshaderId\fP"
.br
.ti -1c
.RI "GLuint \fBcameraPosition\fP"
.br
.ti -1c
.RI "GLuint \fBlightPosition\fP"
.br
.ti -1c
.RI "GLuint \fBlightColor\fP"
.br
.ti -1c
.RI "GLuint \fBlightInfo\fP"
.br
.ti -1c
.RI "GLuint \fBtexturePosition\fP"
.br
.ti -1c
.RI "GLuint \fBnumLights\fP"
.br
.ti -1c
.RI "GLuint \fBbaseColor\fP"
.br
.ti -1c
.RI "GLuint \fBprojMat\fP"
.br
.ti -1c
.RI "GLuint \fBviewMat\fP"
.br
.ti -1c
.RI "GLuint \fBmoveMat\fP"
.br
.ti -1c
.RI "GLuint \fBmodelMat\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Shader program uniform ids\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
