.TH "src/shader.h" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/shader.h \- Shader file loader and compiler (header)  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "GLuint \fBshaderAttachFromFile\fP (GLuint program, GLenum type, const char *filePath)"
.br
.RI "Load and attach shader program\&. "
.in -1c
.SH "Detailed Description"
.PP 
Shader file loader and compiler (header) 


.PP
\fBAuthor:\fP
.RS 4
Gerviba (Szabo Gergely) 
.RE
.PP
\fBDefinition:\fP
.RS 4
\fBshader\&.c\fP 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "GLuint shaderAttachFromFile (GLuint program, GLenum type, const char * filePath)"

.PP
Load and attach shader program\&. 
.PP
\fBParameters:\fP
.RS 4
\fIprogram\fP identifier 
.br
\fItype\fP Vertex or Fragment shader 
.br
\fIfilePath\fP The shader file's path 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
