.TH "src/shader.c" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/shader.c \- Shader file loader and compiler\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stddef\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <gl\&.h>\fP
.br
\fC#include <glext\&.h>\fP
.br
\fC#include 'stdgame\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static char * \fBshaderLoadSource\fP (const char *filePath)"
.br
.RI "Load shader from file\&. "
.ti -1c
.RI "static GLuint \fBshaderCompileFromFile\fP (GLenum type, const char *filePath)"
.br
.RI "Compile shader program\&. "
.ti -1c
.RI "GLuint \fBshaderAttachFromFile\fP (GLuint program, GLenum type, const char *filePath)"
.br
.RI "Load and attach shader program\&. "
.in -1c
.SH "Detailed Description"
.PP 
Shader file loader and compiler\&. 


.PP
\fBAuthor:\fP
.RS 4
Gerviba (Szabo Gergely) 
.RE
.PP
\fBHeader:\fP
.RS 4
\fBshader\&.h\fP 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "GLuint shaderAttachFromFile (GLuint program, GLenum type, const char * filePath)"

.PP
Load and attach shader program\&. 
.PP
\fBParameters:\fP
.RS 4
\fIprogram\fP identifier 
.br
\fItype\fP Vertex or Fragment shader 
.br
\fIfilePath\fP The shader file's path 
.RE
.PP

.SS "static GLuint shaderCompileFromFile (GLenum type, const char * filePath)\fC [static]\fP"

.PP
Compile shader program\&. 
.PP
\fBParameters:\fP
.RS 4
\fItype\fP Vertex or Fragment shader 
.br
\fIfilePath\fP The shader file's path 
.RE
.PP

.SS "static char* shaderLoadSource (const char * filePath)\fC [static]\fP"

.PP
Load shader from file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfilePath\fP The shader file's path 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
