.TH "Spells" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Spells \- \fBSpells\fP storage\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <player\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSpell\fP \fBspell1\fP"
.br
.ti -1c
.RI "\fBSpell\fP \fBspell2\fP"
.br
.ti -1c
.RI "\fBSpell\fP \fBspell3\fP"
.br
.ti -1c
.RI "\fBLinkedList\fP \fBmobSpells\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBSpells\fP storage\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
