.TH "Spell" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Spell \- \fBSpell\fP type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <player\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GLint \fBid\fP"
.br
.ti -1c
.RI "\fBDynamicObject\fP * \fBspellObj\fP"
.br
.ti -1c
.RI "\fBDynamicObjectInstance\fP * \fBspellObjInstance\fP"
.br
.ti -1c
.RI "GLfloat \fBspeed\fP"
.br
.ti -1c
.RI "GLfloat \fBdamage\fP"
.br
.ti -1c
.RI "time_t \fBlastUse\fP"
.br
.ti -1c
.RI "time_t \fBreloadTime\fP"
.br
.ti -1c
.RI "\fBPosition\fP \fBposition\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBSpell\fP type\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
