.TH "StaticObjectPart" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StaticObjectPart \- Cube part of the objects\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <object\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPartType\fP \fBtype\fP"
.br
.ti -1c
.RI "GLfloat * \fBcolor\fP"
.br
.ti -1c
.RI "GLfloat \fBposition\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Cube part of the objects\&. 

The smallest unit
.PP
Used in all the three object types\&. 
.PP
\fBSee also:\fP
.RS 4
\fBStaticObject\fP 
.PP
\fBDynamicObject\fP 
.PP
\fBActiveObject\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
