.TH "Texture" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Texture \- Loaded texture\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <map\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "GLuint \fBtextureId\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Loaded texture\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
