.TH "TextureBlock" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TextureBlock \- Block sides textures\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <map\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "\fBTexture\fP * \fBbase\fP"
.br
.ti -1c
.RI "\fBTexture\fP * \fBtop\fP"
.br
.ti -1c
.RI "\fBTexture\fP * \fBright\fP"
.br
.ti -1c
.RI "\fBTexture\fP * \fBbottom\fP"
.br
.ti -1c
.RI "\fBTexture\fP * \fBleft\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Block sides textures\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
