.TH "TextComponent" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TextComponent \- Text type component specific values\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <components\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFontSize\fP \fBfontSize\fP"
.br
.ti -1c
.RI "char * \fBtext\fP"
.br
.ti -1c
.RI "GLfloat \fBcolor\fP [4]"
.br
.ti -1c
.RI "GLfloat \fBbaseColor\fP [4]"
.br
.ti -1c
.RI "\fBAlign\fP \fBalign\fP"
.br
.ti -1c
.RI "GLfloat \fBrawMax\fP [3]"
.br
.ti -1c
.RI "GLfloat \fBrawMin\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Text type component specific values\&. 


.PP
\fBSee also:\fP
.RS 4
\fBComponent\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
