.TH "Tile" 3 "Tue Dec 5 2017" "stdgame" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tile \- \fBMap\fP tile\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <map\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "\fBTextureBlock\fP * \fBtexture\fP"
.br
.ti -1c
.RI "\fBTileType\fP \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBMap\fP tile\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for stdgame from the source code\&.
